create database Backend
go
use Backend
go

create table DANGKYSACH
(	
	IDDANGKYSACH INT NOT NULL,
	MADANGKYSACH CHAR (50) not null ,     
	SOLUONGSACH int not null,
	TENTACGIA nvarchar (100) not null ,
	THELOAI nvarchar (100),
	NGAYXUATBAN date not null
	PRIMARY KEY (IDDANGKYSACH)


)
go

create table SACH
(	
	
	SACH CHAR (50) NOT NULL   ,
	NHAXUATBAN NVARCHAR (100) NOT NULL  ,
	TENSACH NVARCHAR (100) NOT NULL,
	SOTRANG NVARCHAR (100) NOT NULL,
	TINHTRANG NVARCHAR (100) DEFAULT N'CHUA CO AI THUE'
	primary key (SACH)
	

	

)
go
-- xử lý dữ liệu
alter table dbo.SACH add constraint FK_SACH foreign key (MASACH) REFERENCES dbo.DANGKYSACH(MADANGKYSACH)
alter table dbo.DANGKYSACH ADD CONSTRAINT FK_DANGKYSACH  foreign key (MADANGKYSACH) REFERENCES dbo.SACH(SACH)
drop table SACH
drop table DANGKYSACH
alter table dbo.SACH drop FK_SACH
alter table dbo.DANGKYSACH drop FK_DANGKYSACH
go




-- INSERT DANGKYSACH
INSERT INTO dbo.DANGKYSACH (IDDANGKYSACH, MADANGKYSACH, SOLUONGSACH, TENTACGIA, THELOAI, NGAYXUATBAN)
VALUES 
    (0, 'MS123', 9, N'NGUYEN VAN A', N'KDRAMA', '2024-05-01'); 

INSERT INTO dbo.DANGKYSACH (IDDANGKYSACH, MADANGKYSACH, SOLUONGSACH, TENTACGIA, THELOAI, NGAYXUATBAN)
VALUES 
    (1, 'QOT', 10, N'CHÂU GIA HUY', N'KDRAMA', '2024-05-01'); 
INSERT INTO dbo.DANGKYSACH (IDDANGKYSACH, MADANGKYSACH, SOLUONGSACH, TENTACGIA, THELOAI, NGAYXUATBAN)
VALUES 
    (2, 'RBR', 11, N'PHUNG THAI SON', N'KDRAMA', '2004-05-01'); 
INSERT INTO dbo.DANGKYSACH (IDDANGKYSACH, MADANGKYSACH, SOLUONGSACH, TENTACGIA, THELOAI, NGAYXUATBAN)
VALUES 
    (3, 'VCZ', 12, N'LE AN', N'HANHDONG', '2004-01-01');
	INSERT INTO dbo.DANGKYSACH (IDDANGKYSACH, MADANGKYSACH, SOLUONGSACH, TENTACGIA, THELOAI, NGAYXUATBAN)
VALUES 
    (4, 'ITC', 16, N'LE AN', N'HANHDONG', '2004-01-01');



INSERT INTO dbo.SACH (SACH, NHAXUATBAN, TENSACH, SOTRANG, TINHTRANG)
VALUES 
    ('MS123', N'Nhà Xuất Bản A', N'Tên Sách A', N'100', N'CHUA CO AI THUE')
INSERT INTO dbo.SACH (SACH, NHAXUATBAN, TENSACH, SOTRANG, TINHTRANG)
VALUES 
    ('QOT', N'Nhà Xuất Bản HÀN QUỐC', N'QUEEN OF TEARS', N'500', N'CHUA CO AI THUE')
INSERT INTO dbo.SACH (SACH, NHAXUATBAN, TENSACH, SOTRANG, TINHTRANG)
VALUES 
    ('RBR', N'Nhà Xuất Bản HÀN QUỐC', N'REBORN RICH', N'500', N'CHUA CO AI THUE')
INSERT INTO dbo.SACH (SACH, NHAXUATBAN, TENSACH, SOTRANG, TINHTRANG)
VALUES 
    ('VCZ', N'Nhà Xuất Bản HÀN QUỐC', N'VINCENZO', N'500', N'CHUA CO AI THUE')
	INSERT INTO dbo.SACH (SACH, NHAXUATBAN, TENSACH, SOTRANG, TINHTRANG)
VALUES 
    ('ITC', N'Nhà Xuất Bản TvN', N'Itawon Class', N'500', N'Phan Đức Thọ')


	

